# Generated by Django 6.0.5 on 2026-05-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0002_redsocial_created_redsocial_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redsocial',
            options={'verbose_name': 'Red social', 'verbose_name_plural': 'Redes sociales'},
        ),
    ]
