# Generated by Django 6.0.5 on 2026-05-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_created_services_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
