# Generated by Django 6.0.5 on 2026-05-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_created_category_updated_post_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
    ]
